name: crocolingo
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  get_it: ^7.6.0
  injectable: ^2.1.2
  shared_preferences: ^2.2.0
  go_router: ^9.0.3
  collection: ^1.17.1
  flutter_gen: ^5.3.1
  flutter_svg: ^2.0.7
  dio: ^5.2.1+1
  file_picker: ^5.3.2
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.6
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300